### ISSUE TITLE
Returns 404 ? 

### ISSUE THREAD

**Issue by h0lybyte** [NicolasSiver/nodebb-plugin-ns-login#1]
https://kbve.com/api/ns/login

Returns a 404 , specifically 
"{"path":"&#x2F;ns&#x2F;login","title":"[[global:404.title]]"}"

**Comment by NicolasSiver** [comment]
Do you use `POST` method?
If you are trying to visit URL just in your browser, It's a GET request.

**Comment by h0lybyte** [comment]
So I sent out a couple curl request, it processed it and say it was successfuls, then i sent the same one again (after 4-5 times) and the bruteforce protection said too many failed attempts, even though it was the same exact data. Is the protection before it checks if its successful or not?

**Comment by NicolasSiver** [comment]
Yes, brute-force protection is a safe guard for the server. If it will be performed after login operation it will not have a value.
