### ISSUE TITLE
Using this to integrate with Rocket Chat

### ISSUE THREAD

**Issue by fais3000** [NicolasSiver/nodebb-plugin-ns-login#12]
Hi @NicolasSiver. 

This isn't an issue but a question perhaps. 

Do you think it is possible to use this plugin to let users on Rocket Chat sign in using https://rocket.chat/docs/developer-guides/iframe-integration/authentication/#what-is-iframe-auth

**Comment by NicolasSiver** [comment]
Hello,

Could you ask Rocket Chat developers if such authentication will work? Rocket Chat developer would have more context.

Thanks
