### ISSUE TITLE
Warning plugin is not compatible with 1.12.1

### ISSUE THREAD

**Issue by saesrpgmta** [NicolasSiver/nodebb-plugin-ns-login#16]
Not sure if you need to update anything other than up issuing what version is it compatible with.

**Comment by NicolasSiver** [comment]
Try to do a force install. (`npm install nodebb-plugin-ns-login`)
Lately (last year or two), plugins break quite often with new NodeBB releases.
Now it's up to the users to use the plugin with the version which is not supported by the plugin.
