### ISSUE TITLE
Can't Access the API

### ISSUE THREAD

**Issue by ghost** [NicolasSiver/nodebb-plugin-ns-login#2]
I've installed this on the latest NodeBB and I can't access the API from domain.com/api/ns/login -> I get a 404 not found.. Any ideas?

**Comment by NicolasSiver** [comment]
Yes. Do you try to open an URL in browser? If yes, it's a `GET` request. While `/api/ns/login` is a `POST`

**Comment by ghost** [comment]
My bad, thanks for the help, any idea why it may be a bit slow?

**Comment by NicolasSiver** [comment]
It will take some time. It's a login, there is an authorization process, which isn't the fastest operation that you could have in the system.

**Comment by ghost** [comment]
@NicolasSiver Okay thank you very much for the information :)
