### ISSUE TITLE
Too many failed attempts error message even when logging in correctly

### ISSUE THREAD

**Issue by RoiEXLab** [NicolasSiver/nodebb-plugin-ns-login#5]
Using curl I issued the exact same command with the exact same POST data 5 times, the first 4 times everything works as expected, but the fifth time I get the anti brute force message...
Very annoying when it comes to developing...

**Comment by NicolasSiver** [comment]
I understand. But do you have ideas how to make it better?
Because if brute-force protection will be after a response, it means you can create a huge load on the server.

As an option, you could just comment these lines while you are developing - https://github.com/NicolasSiver/nodebb-plugin-ns-login/blob/master/plugin/index.js#L42-L47

**Comment by RoiEXLab** [comment]
I'd suggest a checkbox with a setting. If checked, the server will validate the request and then increase the timer... if not, the current behaviour will be chosen (with another if more)

**Comment by ilblog** [comment]
Hi Nicolas. I have also found this as a issue while developing. I think that at the end of login process (if login is succesfull) you should remove username from `BruteForce` memory store. I do not know if BruteForce has it as method.

**Comment by NicolasSiver** [comment]
As I understand, setting `ignoreIP` solves a development challenge?

**Comment by ilblog** [comment]
Yes and is necessary for using api internally 

IL

**Comment by alejandrocobo** [comment]
Same over here. As @ilblog have said, would be great if every time a user logs successfully, the user counter goes to initial value. Enabling IgnoreIP does not solve this issue.

Thanks.

**Comment by Julien00859** [comment]
+1 for a checkbox
