### ISSUE TITLE
no sessions

### ISSUE THREAD

**Issue by Jorgeewa** [NicolasSiver/nodebb-plugin-ns-login#6]
I am using nodebb for the community section in another app.

I want user to be logged in when he logs into my app. I simultaneously log in using ns-login but if I visit the forum address on the same browser, the user is not logged in.

I checked the res.body and status is offline even after signing me in. How do I resolve this issue?

**Comment by NicolasSiver** [comment]
This plugin does not provide support for sessions. You could ask a community how to build an application with shared session - https://community.nodebb.org/

This plugin just gives an interface to check credentials.
