### ISSUE TITLE
Can't login using email - Intended or not?

### ISSUE THREAD

**Issue by RoiEXLab** [NicolasSiver/nodebb-plugin-ns-login#9]
The "username input" is [slugified immediately](https://github.com/NicolasSiver/nodebb-plugin-ns-login/blob/master/plugin/index.js#L67) without checking if this provided string is an email adress...
[Your description](https://github.com/NicolasSiver/nodebb-plugin-ns-login#properties) states, that logging in via email should be possible...
Either you should change your README, or re-implement this feature since it seems to be broken...

Also, please change [this line](https://github.com/NicolasSiver/nodebb-plugin-ns-login/blob/master/plugin/index.js#L73) to `'User ' + username + ' does not exist'`

**Comment by NicolasSiver** [comment]
Yep, documentation is ambitious. 
Feature to login via email is not provided by the plugin.
The feature will be added soon.
